language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6

    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install xorg-dev
script: 
  - ./configure
  - make
  - sudo make install
